import winsound
import time
import time

start_time = time.time() #inicia a contar o tempo
i=1
frequency = 440  # Set Frequency To 2500 Hertz
duration = 2500  # Set Duration To 1000 ms == 1 second
duration2 = 500
duration3 = 333
while(i==1):
    print("Pare sua atividades por alguns segundos.")
#    winsound.Beep(frequency, duration3)
#    winsound.Beep(frequency, duration3)
#    winsound.Beep(frequency, duration3)
#    winsound.Beep(frequency, duration3)
#    winsound.Beep(frequency, duration3)
    print("Olhe para longo em...")
    print("5 segundos...")
    time.sleep(1)
    print("4 segundos...")
    time.sleep(1)
    print("3 segundos...")
    time.sleep(1)
    print("2 segundos...")
    time.sleep(1)
    print("1 segundos...")
    time.sleep(1)
	#    winsound.Beep(frequency, duration)
    print("VAMOS LÁ...")
    winsound.Beep(frequency, duration)
    print("OLHE PARA LONGE POR 20 SEGUNDOS")
    time.sleep(1)
    print("OLHE PARA LONGE POR 19 SEGUNDOS")
    time.sleep(1)
    print("OLHE PARA LONGE POR 18 SEGUNDOS")
    time.sleep(1)
    print("OLHE PARA LONGE POR 17 SEGUNDOS")
    time.sleep(1)
    print("OLHE PARA LONGE POR 16 SEGUNDOS")
    time.sleep(1)
    print("OLHE PARA LONGE POR 15 SEGUNDOS")
    time.sleep(1)
    print("OLHE PARA LONGE POR 14 SEGUNDOS")
    time.sleep(1)
    print("OLHE PARA LONGE POR 13 SEGUNDOS")
    time.sleep(1)
    print("OLHE PARA LONGE POR 12 SEGUNDOS")
    time.sleep(1)
    print("OLHE PARA LONGE POR 11 SEGUNDOS")
    time.sleep(1)
    print("OLHE PARA LONGE POR 10 SEGUNDOS")
#    winsound.Beep(frequency, duration2)
    time.sleep(1)
    print("OLHE PARA LONGE POR 9 SEGUNDOS")
    time.sleep(1)
    print("OLHE PARA LONGE POR 8 SEGUNDOS")
    time.sleep(1)
    print("OLHE PARA LONGE POR 7 SEGUNDOS")
    time.sleep(1)
    print("OLHE PARA LONGE POR 6 SEGUNDOS")
    time.sleep(1)
    print("OLHE PARA LONGE POR 5 SEGUNDOS")
    time.sleep(1)
#    winsound.Beep(frequency, duration)
    print("OLHE PARA LONGE POR 4 SEGUNDOS")
    time.sleep(1)
#    winsound.Beep(frequency, duration)
    print("OLHE PARA LONGE POR 3 SEGUNDOS")
    time.sleep(1)
#    winsound.Beep(frequency, duration)
    print("OLHE PARA LONGE POR 2 SEGUNDOS")
    time.sleep(1)
#    winsound.Beep(frequency, duration)
    print("OLHE PARA LONGE POR 1 SEGUNDOS")
    time.sleep(1)
#    winsound.Beep(frequency, duration)
    print("OLHE PARA LONGE POR 0 SEGUNDOS")    
    winsound.Beep(frequency, duration3)
    time.sleep(1)
    print("PRONTO! SEU OLHOS ESTÃO MAIS DESCANÇADOS...   :)")
    time.sleep(1)
    print("Em cerca de 20 min outro aviso aparecerá")
    time.sleep(1172)    #espera cerca de 20 min
