n=float(input('Digite um valor: '))
print(type(n))




if n.isalpha()
    print('É alfabético')
if n.isdecimal()
    print('É decimal')
if n.isdigit()
    print('É digito')
if n.isidentifier()
    print('É identificador')
if n.islower()
    print('É tudo minúsculo')
if n.isnumeric()
    print('É numérico')
if n.isprintable()
    print('É imprimível')
if n.isspace()
    print('É espaço')
if n.isupper()
    print('É maiúscula')
if n.istitle()
    print('É título')